# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make dep
builds:
  - main: ./
    id: &name minecraft-preempt
    binary: *name
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - '-w -s -X "github.com/getoutreach/go-outreach/v2/pkg/app.Version={{ .Version }}"'
    env:
      - CGO_ENABLED=0
archives: []
checksum:
  name_template: "checksums.txt"
