# Cloud to use, must have the relevant cloudConfig block
# filled out.
cloud: docker
cloudConfig:
  gcp:
    # GCP ONLY RIGHT NOW
    # ID of your instance
    instanceID: 3221088494815516132

    # GCP Project
    project: triton-ops

    # GCP Zone
    zone: us-west1-b

  docker:
    # Docker container to start / get the status of
    containerID: fixme
server:
  hostname: 127.0.0.1
  port: 25566

  # Get from here: https://wiki.vg/Protocol_History
  protocolVersion: 578
  textVersion: 1.15.2
