# These run only on PR events, and can't run on push
name: PR Linters

on:
  pull_request:

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    name: "PR Title"
    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
