name: Lifecycle

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release-dryrun:
    name: Release (Dry-run)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.14"
      - name: Environment Details
        run: go version && node --version
      - name: Install Dependencies
        run: NODE_ENV=development yarn
      - name: Release
        run: |-
          export GITHUB_EVENT_NAME=push
          export GITHUB_REF=main
          git checkout -b main
          yarn semantic-release --dry-run

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - release-dryrun
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.14"
      - name: Environment Details
        run: go version && node --version
      - name: Install Dependencies
        run: NODE_ENV=development yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
