name: Lifecycle

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release-dryrun:
    name: Release (Dry-run)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tool Versions
        uses: asdf-vm/actions/install@v1
      - name: Install Dependencies
        run: NODE_ENV=development yarn --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then 
            export GITHUB_EVENT_NAME=push
            export GITHUB_REF=main
            git checkout -b main || true
          fi

          yarn semantic-release --dry-run
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - release-dryrun
    steps:
      - uses: actions/checkout@v3
      - name: Install Tool Versions
        uses: asdf-vm/actions/install@v1
      - name: Install Dependencies
        run: NODE_ENV=development yarn --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
